language: php
php:
  - "5.4"
  - "5.3"
before_script:
  - git clone --depth=50 --branch=master git://github.com/Arcavias/arcavias-core.git ../arcavias-core
  - cd ../arcavias-core
  - mv ../ext-typo3 ext/typo3
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install
  - pear channel-discover pear.phing.info
  - pear install phing/phing
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - mysql -e 'create database arcavias;'
  - cp config/.resource.php.ci config/resource.php
script: "phing setup && phing -Ddir=ext/typo3 testext && phing -Ddir=ext/typo3 checkext"
